import { useEffect, useMemo, useState } from 'react'
import { api } from '../../api'
import { useApp } from '../../context'
import { Card, Button, AnonBadge, TagPill, EmptyState, SearchBar, SelectField, IconBook } from '../../components/ui'
type Review = { _id: string; anonymous: boolean; text: string; tags: string[]; createdAt: string; course: { code: string; title: string }; ratings: Record<string, number> }
type Course = { _id: string; code: string; title: string }
const date = (value: string) => new Intl.DateTimeFormat(undefined, { month: 'short', year: 'numeric', day: 'numeric' }).format(new Date(value))
export default function CourseFeedback() {
  const { navigate, token } = useApp(); const [reviews, setReviews] = useState<Review[]>([]); const [courses, setCourses] = useState<Course[]>([]); const [course, setCourse] = useState('all'); const [query, setQuery] = useState('')
  useEffect(() => { if (!token) return; api<{ reviews: Review[] }>('/reviews/teacher', {}, token).then(x => setReviews(x.reviews)).catch(() => {}); api<{ courses: Course[] }>('/courses', {}, token).then(x => setCourses(x.courses)).catch(() => {}) }, [token])
  const visible = useMemo(() => reviews.filter(review => (course === 'all' || review.course?._id === course) && review.text.toLowerCase().includes(query.toLowerCase())), [reviews, course, query])
  return <div className="max-w-5xl mx-auto px-4 sm:px-6 py-8"><div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold font-heading text-fg">Student Feedback</h1><p className="text-sm text-fg-muted">Reviews are shown as students submit them.</p></div><Button onClick={() => navigate('teacher-dashboard')} variant="outline" size="sm">← Dashboard</Button></div><div className="grid lg:grid-cols-3 gap-6"><Card className="p-5"><SelectField label="Course" value={course} onChange={e => setCourse(e.target.value)}><option value="all">All my courses</option>{courses.map(item => <option key={item._id} value={item._id}>{item.code} — {item.title}</option>)}</SelectField></Card><div className="lg:col-span-2 space-y-4"><SearchBar placeholder="Search reviews…" value={query} onChange={setQuery} />{visible.map(review => <Card key={review._id} className="p-4"><div className="flex items-center gap-2 mb-2">{review.anonymous ? <AnonBadge /> : <span className="text-sm font-medium text-fg">Student</span>}<span className="text-xs text-fg-muted">{review.course?.code} · {date(review.createdAt)}</span></div><p className="text-sm text-fg mb-2">{review.text}</p><div className="flex flex-wrap gap-1.5">{review.tags.map(tag => <TagPill key={tag} label={tag} />)}</div></Card>)}{visible.length === 0 && <EmptyState icon={<IconBook className="w-7 h-7" />} title="No reviews yet" description="Student reviews for your assigned courses will appear here." />}</div></div></div>
}
