import { useEffect, useState } from 'react'
import { api } from '../../api'
import { useApp } from '../../context'
import { Card, Button, AnonBadge, StatusChip, Modal, Textarea, EmptyState, Tabs, IconMessage } from '../../components/ui'
type Question = { _id: string; anonymous: boolean; text: string; createdAt: string; course: { code: string; title: string }; answer?: { text: string; answeredAt: string } }
export default function TeacherQA() {
  const { token } = useApp(); const [questions, setQuestions] = useState<Question[]>([]); const [tab, setTab] = useState('Unanswered'); const [selected, setSelected] = useState<Question | null>(null); const [answer, setAnswer] = useState('')
  const load = () => token && api<{ questions: Question[] }>('/questions/teacher', {}, token).then(x => setQuestions(x.questions)).catch(() => {})
  useEffect(() => { load() }, [token])
  const current = questions.filter(question => tab === 'Answered' ? question.answer : !question.answer)
  const submit = () => { if (!token || !selected || !answer.trim()) return; api<{ question: Question }>(`/questions/${selected._id}/answer`, { method: 'POST', body: JSON.stringify({ text: answer }) }, token).then(() => { setSelected(null); setAnswer(''); load() }).catch(() => {}) }
  return <div className="max-w-3xl mx-auto px-4 sm:px-6 py-8"><Modal open={!!selected} onClose={() => setSelected(null)} title="Answer Question"><Textarea label="Your answer" value={answer} onChange={e => setAnswer(e.target.value)} rows={4} /><div className="flex gap-3 mt-4"><Button variant="outline" onClick={() => setSelected(null)} className="flex-1">Cancel</Button><Button onClick={submit} disabled={!answer.trim()} className="flex-1">Post answer</Button></div></Modal><h1 className="text-2xl font-bold font-heading text-fg">Q&A Management</h1><p className="text-sm text-fg-muted mb-6">Answer questions from your assigned courses.</p><Tabs tabs={['Unanswered', 'Answered']} active={tab} onChange={setTab} /><div className="space-y-4 mt-4">{current.map(question => <Card key={question._id} className="p-4"><div className="flex justify-between gap-3 mb-2"><div className="flex items-center gap-2">{question.anonymous ? <AnonBadge /> : <span className="text-sm">Student</span>}<span className="text-xs text-fg-muted">{question.course.code}</span></div><StatusChip status={question.answer ? 'answered' : 'unanswered'} /></div><p className="text-sm text-fg">{question.text}</p>{question.answer ? <div className="bg-accent-tint rounded-xl p-3 mt-3 text-sm">{question.answer.text}</div> : <Button size="sm" className="mt-3" onClick={() => setSelected(question)}>Answer</Button>}</Card>)}{current.length === 0 && <EmptyState icon={<IconMessage className="w-7 h-7" />} title={`No ${tab.toLowerCase()} questions`} description="Questions submitted by students will appear here." />}</div></div>
}
