import { useEffect, useState } from 'react'
import { api } from '../../api'
import { useApp } from '../../context'
import { Button, Card, EmptyState, IconBook, SelectField, StarDisplay, Textarea, Toggle } from '../../components/ui'

type Course = { _id: string; code: string; title: string; credits: number; semester?: string; teacher?: { name: string } }
type Review = { _id: string; text: string; ratings: Record<string, number>; anonymous: boolean; author?: { name: string }; createdAt: string }
type Question = { _id: string; text: string; answer?: { text?: string; teacher?: { name: string } } }

export default function CourseDetail() {
  const { navigate, navParams, token } = useApp(); const courseId = navParams?.courseId; const [course, setCourse] = useState<Course | null>(null); const [reviews, setReviews] = useState<Review[]>([]); const [questions, setQuestions] = useState<Question[]>([]); const [reviewText, setReviewText] = useState(''); const [rating, setRating] = useState('5'); const [anonymousReview, setAnonymousReview] = useState(true); const [questionText, setQuestionText] = useState(''); const [error, setError] = useState('')
  const load = () => { if (!token || !courseId) return; Promise.all([api<{ course: Course }>(`/courses/${courseId}`, {}, token), api<{ reviews: Review[] }>(`/courses/${courseId}/reviews`, {}, token), api<{ questions: Question[] }>(`/courses/${courseId}/questions`, {}, token)]).then(([courseData, reviewData, questionData]) => { setCourse(courseData.course); setReviews(reviewData.reviews); setQuestions(questionData.questions) }).catch(value => setError(value instanceof Error ? value.message : 'Unable to load course')) }
  useEffect(() => { load() }, [token, courseId])
  const submitReview = () => { const value = Number(rating); return token && courseId && api(`/courses/${courseId}/reviews`, { method: 'POST', body: JSON.stringify({ text: reviewText, ratings: { teachingQuality: value, workload: value, gradingFairness: value, courseStructure: value, availability: value }, anonymous: anonymousReview }) }, token).then(() => { setReviewText(''); load() }).catch(value => setError(value instanceof Error ? value.message : 'Unable to submit review')) }
  const submitQuestion = () => token && courseId && api(`/courses/${courseId}/questions`, { method: 'POST', body: JSON.stringify({ text: questionText, anonymous: true }) }, token).then(() => { setQuestionText(''); load() }).catch(value => setError(value instanceof Error ? value.message : 'Unable to submit question'))
  if (!courseId) return <div className="max-w-4xl mx-auto px-4 py-8"><EmptyState icon={<IconBook className="w-7 h-7" />} title="No course selected" action={<Button onClick={() => navigate('student-dashboard')}>Browse courses</Button>} /></div>
  return <div className="max-w-4xl mx-auto px-4 sm:px-6 py-8"><button onClick={() => navigate('student-dashboard')} className="text-sm text-brand mb-5">← Back to Browse</button>{error && <p role="alert" className="text-sm text-danger mb-4">{error}</p>}{course && <Card className="p-5 mb-6"><p className="text-xs font-semibold text-brand">{course.code}</p><h1 className="text-2xl font-bold font-heading mt-1">{course.title}</h1><p className="text-sm text-fg-muted mt-2">{course.teacher?.name ?? 'Teacher not assigned'} · {course.credits} credits {course.semester ? `· ${course.semester}` : ''}</p></Card>}<div className="grid lg:grid-cols-2 gap-6"><section><h2 className="font-semibold text-lg mb-3">Reviews</h2><SelectField label="Overall rating" value={rating} onChange={event => setRating(event.target.value)}>{[5, 4, 3, 2, 1].map(value => <option key={value} value={value}>{value} star{value === 1 ? '' : 's'}</option>)}</SelectField><Textarea label={anonymousReview ? 'Write an anonymous review' : 'Write a named review'} value={reviewText} onChange={event => setReviewText(event.target.value)} /><div className="mt-3"><Toggle checked={anonymousReview} onChange={setAnonymousReview} label="Post anonymously" hint="Turn this off to publish your name with the review." /></div><Button className="mt-3" disabled={!reviewText.trim()} onClick={submitReview}>Submit review</Button><div className="space-y-3 mt-5">{reviews.map(review => { const values = Object.values(review.ratings); return <Card key={review._id} className="p-4"><div className="flex items-center justify-between gap-3"><StarDisplay value={values.reduce((sum, value) => sum + value, 0) / values.length} /><span className="text-xs text-fg-muted">{review.anonymous ? 'Anonymous' : review.author?.name ?? 'Student'}</span></div><p className="text-sm text-fg-muted mt-2">{review.text}</p></Card>})}{!reviews.length && <EmptyState title="No reviews yet" description="Be the first to share feedback." />}</div></section><section><h2 className="font-semibold text-lg mb-3">Q&A</h2><Textarea label="Ask an anonymous question" value={questionText} onChange={event => setQuestionText(event.target.value)} /><Button className="mt-3" disabled={!questionText.trim()} onClick={submitQuestion}>Post question</Button><div className="space-y-3 mt-5">{questions.map(question => <Card key={question._id} className="p-4"><p className="text-sm text-fg">{question.text}</p>{question.answer?.text ? <p className="text-sm text-fg-muted mt-3"><strong>{question.answer.teacher?.name ?? 'Teacher'}:</strong> {question.answer.text}</p> : <p className="text-xs text-fg-muted mt-3">Awaiting an answer</p>}</Card>)}{!questions.length && <EmptyState title="No questions yet" description="Ask the first question." />}</div></section></div></div>
}
