import { useEffect, useState } from 'react'
import { api } from '../../api'
import { useApp } from '../../context'
import { Avatar, Card, EmptyState, IconBook, IconMessage, SearchBar } from '../../components/ui'

type Course = { _id: string; code: string; title: string; credits: number; semester?: string; department: string; teacher?: { name: string; department: string } }
type Professor = { _id: string; name: string; department: string }

export default function StudentDashboard() {
  const { navigate, token } = useApp(); const [tab, setTab] = useState<'courses' | 'professors'>('courses'); const [query, setQuery] = useState(''); const [courses, setCourses] = useState<Course[]>([]); const [professors, setProfessors] = useState<Professor[]>([]); const [error, setError] = useState('')
  useEffect(() => { if (token) Promise.all([api<{ courses: Course[] }>(`/courses?q=${encodeURIComponent(query)}`, {}, token), api<{ professors: Professor[] }>('/admin/professors', {}, token)]).then(([courseData, professorData]) => { setCourses(courseData.courses); setProfessors(professorData.professors) }).catch(value => setError(value instanceof Error ? value.message : 'Unable to load courses')) }, [token, query])
  const filteredProfessors = professors.filter(professor => professor.name.toLowerCase().includes(query.toLowerCase()))
  return <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8"><h1 className="text-2xl font-bold font-heading text-fg mb-1">Discover Courses & Professors</h1><p className="text-sm text-fg-muted mb-6">Your department’s courses, professor profiles, reviews, and Q&A.</p><SearchBar placeholder={tab === 'courses' ? 'Search courses…' : 'Search professors…'} value={query} onChange={setQuery} /><div className="flex gap-1 border-b border-line my-6">{(['courses', 'professors'] as const).map(item => <button key={item} onClick={() => setTab(item)} className={`px-4 py-2.5 text-sm font-medium capitalize border-b-2 -mb-px ${tab === item ? 'text-brand border-brand' : 'text-fg-muted border-transparent'}`}>{item}</button>)}</div>{error && <p role="alert" className="text-sm text-danger mb-4">{error}</p>}{tab === 'courses' ? <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{courses.map(course => <Card key={course._id} onClick={() => navigate('student-course-detail', { courseId: course._id })} className="p-5"><p className="text-xs font-semibold text-brand">{course.code}</p><h2 className="font-semibold text-fg mt-1">{course.title}</h2><p className="text-sm text-fg-muted mt-2">{course.teacher?.name ?? 'Teacher not assigned'} · {course.credits} credits</p>{course.semester && <p className="text-xs text-fg-muted mt-1">{course.semester}</p>}</Card>)}{!courses.length && <div className="md:col-span-2 lg:col-span-3"><EmptyState icon={<IconBook className="w-7 h-7" />} title="No courses found" description="Courses added by your administrator appear here." /></div>}</div> : <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{filteredProfessors.map(professor => <Card key={professor._id} className="p-5"><div className="flex gap-3"><Avatar name={professor.name} /><div><h2 className="font-semibold text-fg">{professor.name}</h2><p className="text-sm text-fg-muted">{professor.department}</p></div></div></Card>)}{!filteredProfessors.length && <div className="md:col-span-2 lg:col-span-3"><EmptyState icon={<IconMessage className="w-7 h-7" />} title="No professors found" description="Professor records added by the administrator appear here." /></div>}</div>}</div>
}
