export type Theme = 'light' | 'dark'
export type Role = 'guest' | 'student' | 'teacher' | 'admin'
export type SignupRole = 'student'

export type View =
  | 'landing'
  | 'role-select'
  | 'login'
  | 'signup'
  | 'otp'
  | 'forgot-password'
  | 'student-dashboard'
  | 'student-course-detail'
  | 'student-my-reviews'
  | 'student-profile'
  | 'teacher-dashboard'
  | 'teacher-course-feedback'
  | 'teacher-qa'
  | 'teacher-profile'
  | 'admin-dashboard'
  | 'admin-users'
  | 'admin-courses'
  | 'admin-moderation'
  | 'admin-analytics'
  | 'admin-profile'
  | 'terms'
  | 'privacy'
