import { useEffect, useState } from 'react'
import { api } from '../../api'
import { useApp } from '../../context'
import { Card, EmptyState, KpiCard, PageHeader, IconBarChart, IconBook, IconShield, IconUsers } from '../../components/ui'

type Analytics = { metrics: { reviews: number; anonymousRate: number; averageRating: number | null; users: number }; volume: { _id: { year: number; month: number }; count: number }[]; departments: { _id: string; courses: number; reviews: number }[]; topCourses: { courseId: string; code: string; title: string; average: number; reviewCount: number }[]; bottomCourses: { courseId: string; code: string; title: string; average: number; reviewCount: number }[] }
const RatingList = ({ title, courses }: { title: string; courses: Analytics['topCourses'] }) => <Card className="p-5"><h2 className="font-semibold font-heading text-fg mb-4">{title}</h2>{courses.length ? <div className="space-y-2">{courses.map(course => <div key={course.courseId} className="flex justify-between text-sm"><span>{course.code} · {course.title}</span><span className="text-fg-muted">{course.average.toFixed(1)} ({course.reviewCount})</span></div>)}</div> : <EmptyState title="No rating data yet" description="Courses appear after reviews are submitted." />}</Card>

export default function AdminAnalytics() {
  const { token } = useApp(); const [data, setData] = useState<Analytics | null>(null); const [error, setError] = useState('')
  useEffect(() => { if (token) api<Analytics>('/admin/analytics', {}, token).then(setData).catch(value => setError(value instanceof Error ? value.message : 'Unable to load analytics')) }, [token])
  const metrics = data?.metrics
  return <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8"><PageHeader title="Platform Analytics" description="Live data from MongoDB" />{error && <p role="alert" className="text-sm text-danger mb-4">{error}</p>}<div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-8"><KpiCard label="Review Volume" value={metrics?.reviews ?? '—'} sub="all time" icon={<IconBarChart />} color="brand" /><KpiCard label="Anonymous Rate" value={metrics ? `${Math.round(metrics.anonymousRate * 100)}%` : '—'} sub="of posts" icon={<IconShield />} color="anon" /><KpiCard label="Avg. Platform Rating" value={metrics?.averageRating?.toFixed(1) ?? '—'} sub="all courses" icon={<IconBook />} color="accent" /><KpiCard label="Users" value={metrics?.users ?? '—'} sub="registered" icon={<IconUsers />} color="warning" /></div><div className="grid lg:grid-cols-2 gap-6 mb-6"><Card className="p-5"><h2 className="font-semibold mb-4">Review Volume by Month</h2>{data?.volume.length ? data.volume.map(item => <div key={`${item._id.year}-${item._id.month}`} className="flex justify-between text-sm py-1"><span>{item._id.year}-{String(item._id.month).padStart(2, '0')}</span><span>{item.count}</span></div>) : <EmptyState title="No reviews yet" />}</Card><Card className="p-5"><h2 className="font-semibold mb-4">Department Breakdown</h2>{data?.departments.length ? data.departments.map(item => <div key={item._id} className="flex justify-between text-sm py-1"><span>{item._id}</span><span>{item.courses} courses · {item.reviews} reviews</span></div>) : <EmptyState title="No departments yet" />}</Card></div><div className="grid lg:grid-cols-2 gap-6"><RatingList title="Top Rated Courses" courses={data?.topCourses ?? []} /><RatingList title="Lowest Rated Courses" courses={data?.bottomCourses ?? []} /></div></div>
}
