import { useEffect, useState } from 'react'
import { api } from '../../api'
import { useApp } from '../../context'
import { Button, Card, EmptyState, Modal, PageHeader, SelectField, TextField } from '../../components/ui'

type Teacher = { _id: string; name: string; department: string }
type Course = { _id: string; code: string; title: string; credits: number; semester?: string; department: string; teacher: Teacher }
const departments = ['CIVIL', 'EEE', 'ME', 'CSE', 'MIE', 'MME', 'PME', 'WRE', 'BME', 'ETE']
const emptyForm = { code: '', title: '', credits: '3', semester: '', department: 'CSE', teacher: '' }
export default function AdminCourses() {
  const { token } = useApp(); const [courses, setCourses] = useState<Course[]>([]); const [teachers, setTeachers] = useState<Teacher[]>([]); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<Course | null>(null); const [open, setOpen] = useState(false); const [error, setError] = useState('')
  const load = () => { if (!token) return; Promise.all([api<{ courses: Course[] }>('/courses', {}, token), api<{ professors: Teacher[] }>('/admin/professors', {}, token)]).then(([courseData, teacherData]) => { setCourses(courseData.courses); setTeachers(teacherData.professors) }).catch(value => setError(value instanceof Error ? value.message : 'Unable to load courses')) }
  useEffect(() => { load() }, [token])
  const openCreate = () => { setEditing(null); setForm(emptyForm); setError(''); setOpen(true) }
  const openEdit = (course: Course) => { setEditing(course); setForm({ code: course.code, title: course.title, credits: String(course.credits), semester: course.semester ?? '', department: course.department, teacher: course.teacher._id }); setError(''); setOpen(true) }
  const save = () => { if (!token) return; const body = { ...form, credits: Number(form.credits) }; api(editing ? `/courses/${editing._id}` : '/courses', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(body) }, token).then(() => { setOpen(false); load() }).catch(value => setError(value instanceof Error ? value.message : 'Unable to save course')) }
  const remove = (course: Course) => { if (!token || !window.confirm(`Delete ${course.code}? This also removes its reviews and questions.`)) return; api(`/courses/${course._id}`, { method: 'DELETE' }, token).then(load).catch(value => setError(value instanceof Error ? value.message : 'Unable to delete course')) }
  const update = (field: keyof typeof form) => (event: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>) => setForm(current => ({ ...current, [field]: event.target.value }))
  const visibleTeachers = teachers.filter(teacher => teacher.department === form.department)
  return <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8"><PageHeader title="Course Management" description="Courses and department assignments from MongoDB" actions={<Button onClick={openCreate}>Add Course</Button>} />{error && <p role="alert" className="text-sm text-danger mb-4">{error}</p>}<Modal open={open} onClose={() => setOpen(false)} title={editing ? 'Edit Course' : 'Add Course'}><div className="space-y-3"><TextField label="Course code" value={form.code} onChange={update('code')} /><TextField label="Course title" value={form.title} onChange={update('title')} /><TextField label="Credits" type="number" min="0" max="10" value={form.credits} onChange={update('credits')} /><TextField label="Semester" value={form.semester} onChange={update('semester')} /><SelectField label="Department" value={form.department} onChange={update('department')}>{departments.map(department => <option key={department}>{department}</option>)}</SelectField><SelectField label="Teacher" value={form.teacher} onChange={update('teacher')}><option value="">Select a teacher</option>{visibleTeachers.map(teacher => <option key={teacher._id} value={teacher._id}>{teacher.name}</option>)}</SelectField><Button className="w-full" onClick={save} disabled={!form.code || !form.title || !form.teacher}>Save Course</Button></div></Modal><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-bg text-fg-muted"><tr><th className="p-3">Course</th><th className="p-3">Department</th><th className="p-3">Credits</th><th className="p-3">Teacher</th><th className="p-3">Actions</th></tr></thead><tbody>{courses.map(course => <tr key={course._id} className="border-t border-line"><td className="p-3"><p className="font-medium">{course.title}</p><p className="text-xs text-brand">{course.code}</p></td><td className="p-3">{course.department}</td><td className="p-3">{course.credits}</td><td className="p-3">{course.teacher?.name ?? '—'}</td><td className="p-3 flex gap-2"><Button size="sm" variant="outline" onClick={() => openEdit(course)}>Edit</Button><Button size="sm" variant="danger" onClick={() => remove(course)}>Delete</Button></td></tr>)}</tbody></table></div>{!courses.length && <EmptyState title="No courses yet" description="Add the first course and assign a teacher." />}</Card></div>
}
