import { useEffect, useState } from 'react'
import { api } from '../../api'
import { useApp } from '../../context'
import { Button, Card, EmptyState, PageHeader, SearchBar } from '../../components/ui'

type User = { _id: string; name: string; email: string; role: 'student' | 'teacher' | 'admin'; department?: string; active: boolean; createdAt: string }
export default function AdminUsers() {
  const { token } = useApp(); const [users, setUsers] = useState<User[]>([]); const [query, setQuery] = useState(''); const [error, setError] = useState('')
  const load = () => token && api<{ users: User[] }>('/admin/users', {}, token).then(data => setUsers(data.users)).catch(value => setError(value instanceof Error ? value.message : 'Unable to load users'))
  useEffect(() => { load() }, [token])
  const updateStatus = (user: User) => token && api(`/admin/users/${user._id}`, { method: 'PATCH', body: JSON.stringify({ active: !user.active }) }, token).then(load).catch(value => setError(value instanceof Error ? value.message : 'Unable to update user'))
  const filtered = users.filter(user => `${user.name} ${user.email} ${user.department ?? ''}`.toLowerCase().includes(query.toLowerCase()))
  return <div className="max-w-6xl mx-auto px-4 sm:px-6 py-8"><PageHeader title="User Management" description="Live accounts stored in MongoDB" /><SearchBar placeholder="Search name, email, or department…" value={query} onChange={setQuery} /><div className="grid grid-cols-3 gap-3 my-6"><Card className="p-3 text-center"><p className="text-xl font-bold">{users.length}</p><p className="text-xs text-fg-muted">Total users</p></Card><Card className="p-3 text-center"><p className="text-xl font-bold">{users.filter(user => user.role === 'student').length}</p><p className="text-xs text-fg-muted">Students</p></Card><Card className="p-3 text-center"><p className="text-xl font-bold">{users.filter(user => user.role === 'teacher').length}</p><p className="text-xs text-fg-muted">Teachers</p></Card></div>{error && <p role="alert" className="text-sm text-danger mb-4">{error}</p>}<Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-bg text-fg-muted"><tr><th className="p-3">User</th><th className="p-3">Role</th><th className="p-3">Department</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{filtered.map(user => <tr key={user._id} className="border-t border-line"><td className="p-3"><p className="font-medium">{user.name}</p><p className="text-xs text-fg-muted">{user.email}</p></td><td className="p-3 capitalize">{user.role}</td><td className="p-3">{user.department ?? '—'}</td><td className="p-3">{user.active ? 'Active' : 'Suspended'}</td><td className="p-3"><Button size="sm" variant={user.active ? 'danger' : 'secondary'} onClick={() => updateStatus(user)} disabled={user.role === 'admin'}>{user.active ? 'Suspend' : 'Activate'}</Button></td></tr>)}</tbody></table></div>{!filtered.length && <EmptyState title="No users found" />}</Card></div>
}
